package com.slut.simplepass;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTH_INFO".
*/
public class AuthInfoDao extends AbstractDao<AuthInfo, Long> {

    public static final String TABLENAME = "AUTH_INFO";

    /**
     * Properties of entity AuthInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pwd = new Property(1, String.class, "pwd", false, "PWD");
        public final static Property Reservation = new Property(2, String.class, "reservation", false, "RESERVATION");
        public final static Property Create_stamp = new Property(3, Long.class, "create_stamp", false, "CREATE_STAMP");
        public final static Property Update_stamp = new Property(4, Long.class, "update_stamp", false, "UPDATE_STAMP");
    }


    public AuthInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AuthInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTH_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PWD\" TEXT," + // 1: pwd
                "\"RESERVATION\" TEXT," + // 2: reservation
                "\"CREATE_STAMP\" INTEGER," + // 3: create_stamp
                "\"UPDATE_STAMP\" INTEGER);"); // 4: update_stamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTH_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(2, pwd);
        }
 
        String reservation = entity.getReservation();
        if (reservation != null) {
            stmt.bindString(3, reservation);
        }
 
        Long create_stamp = entity.getCreate_stamp();
        if (create_stamp != null) {
            stmt.bindLong(4, create_stamp);
        }
 
        Long update_stamp = entity.getUpdate_stamp();
        if (update_stamp != null) {
            stmt.bindLong(5, update_stamp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(2, pwd);
        }
 
        String reservation = entity.getReservation();
        if (reservation != null) {
            stmt.bindString(3, reservation);
        }
 
        Long create_stamp = entity.getCreate_stamp();
        if (create_stamp != null) {
            stmt.bindLong(4, create_stamp);
        }
 
        Long update_stamp = entity.getUpdate_stamp();
        if (update_stamp != null) {
            stmt.bindLong(5, update_stamp);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AuthInfo readEntity(Cursor cursor, int offset) {
        AuthInfo entity = new AuthInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // pwd
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // reservation
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // create_stamp
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // update_stamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPwd(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReservation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreate_stamp(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setUpdate_stamp(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AuthInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AuthInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AuthInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
