package com.slut.simplepass;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "AUTH_INFO".
 */
public class AuthInfo {

    private Long id;
    private String pwd;
    private String reservation;
    private Long create_stamp;
    private Long update_stamp;

    public AuthInfo() {
    }

    public AuthInfo(Long id) {
        this.id = id;
    }

    public AuthInfo(Long id, String pwd, String reservation, Long create_stamp, Long update_stamp) {
        this.id = id;
        this.pwd = pwd;
        this.reservation = reservation;
        this.create_stamp = create_stamp;
        this.update_stamp = update_stamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getReservation() {
        return reservation;
    }

    public void setReservation(String reservation) {
        this.reservation = reservation;
    }

    public Long getCreate_stamp() {
        return create_stamp;
    }

    public void setCreate_stamp(Long create_stamp) {
        this.create_stamp = create_stamp;
    }

    public Long getUpdate_stamp() {
        return update_stamp;
    }

    public void setUpdate_stamp(Long update_stamp) {
        this.update_stamp = update_stamp;
    }

}
