package com.slut.simplepass;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.slut.simplepass.AuthInfo;

import com.slut.simplepass.AuthInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authInfoDaoConfig;

    private final AuthInfoDao authInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authInfoDaoConfig = daoConfigMap.get(AuthInfoDao.class).clone();
        authInfoDaoConfig.initIdentityScope(type);

        authInfoDao = new AuthInfoDao(authInfoDaoConfig, this);

        registerDao(AuthInfo.class, authInfoDao);
    }
    
    public void clear() {
        authInfoDaoConfig.clearIdentityScope();
    }

    public AuthInfoDao getAuthInfoDao() {
        return authInfoDao;
    }

}
